production:
  adapter: mysql2
  database: redmine
  host: 127.0.0.1
  port: 3306
  username: redmine
  password: "redmine"
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4

development:
  adapter: mysql2
  database: redmine
  host: 127.0.0.1
  port: 3306
  username: redmine
  password: "redmine"
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4

test:
  adapter: mysql2
  database: redmine
  host: 127.0.0.1
  port: 3306
  username: redmine
  password: "redmine"
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
